### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by ky0ncheng** [yanm1ng/hexo-theme-vexo#1]
![](http://wx2.sinaimg.cn/large/6d9bd6a5gy1fggmrob90mj218g0plqq7.jpg)

首頁圖片顯示沒控制寬度

`` 引號內字段沒有css樣式

![](http://wx3.sinaimg.cn/mw1024/6d9bd6a5gy1fggmro8hxxj20lu0hswho.jpg)

代碼段內序號顯示問題，怎麼設置不顯示，根目錄的_config.yml並不能控制

http://yanm1ng.cn/hexo-theme-vexo/archives

歸檔頁面錯誤, 可以參考 https://github.com/pinggod/hexo-theme-apollo/tree/master/layout

**Comment by yanm1ng** [comment]
首先感謝你提出的issue，我會盡快檢查并修復~

**Comment by yanm1ng** [comment]
![image](https://user-images.githubusercontent.com/16443628/27008198-ca8f7524-4e9d-11e7-8c2b-0f0ee6e62ab0.png)
添加了 Archives 頁面

**Comment by ky0ncheng** [comment]
@yanm1ng 
首頁的圖片應該是居中，不應該是居左。
另外，圖片在文章內，應和上方下方的文字空出一個 `換行` 的距離。

文章內頁的圖片居中了，這個正常。

首頁代碼塊背景白色，bug？
style.styl
`.hljs
  background: #f8f8f8
  font-size: 1em`

**Comment by yanm1ng** [comment]
修改好了，發現原來是沒有考慮到有文章摘要時的情況。感謝你的提醒

**Comment by ky0ncheng** [comment]
非常棒
