### ISSUE TITLE
在页面出现顶部出现 css('css/plugins/gitment.css') 怎么解决呢

### ISSUE THREAD

**Issue by mkfoyw** [yanm1ng/hexo-theme-vexo#107]

**Comment by xugaoxiang** [comment]
https://github.com/yanm1ng/hexo-theme-vexo/issues/98

**Comment by luohao07** [comment]
这个像是评论插件的css，我不用评论就直接改_config.yml文件把评论去掉了

**Comment by yanm1ng** [comment]
注释掉就行了

**Comment by fuzz-sec** [comment]
themes/vexo/layout/_partial/head.ejs  23行，改为:`<%-   css('css/plugins/gitment.css') %>`

**Comment by TryHard3r** [comment]
> 注释掉就行了

注释掉还是不行
