### ISSUE TITLE
文章的tag添加链接

### ISSUE THREAD

**Issue by calvingit** [yanm1ng/hexo-theme-vexo#12]
如题

**Comment by yanm1ng** [comment]
你可以提一个 pr 😊

**Comment by calvingit** [comment]
我不太懂前端啊😓 ，我知道在**tag.ejs**里面改

```
<% tags.each(function(tag) { %>
  <span class="tag-code"><a href="<%- url_for(config.root + config.tag_dir)%>"><%= tag.name %></a></span>
<% }) %>
```
但是我加了a标签之后，只能跳转到tags下面，再也没法做到跳转到指定的锚点 了，比如

`http://example.com/tags#tag-1`

**Comment by calvingit** [comment]
我搞好了，[https://github.com/calvingit/hexo-theme-vexo/commit/42d1b2bb867e0f614e6d0cd30eaa5725cc852f32](https://github.com/calvingit/hexo-theme-vexo/commit/42d1b2bb867e0f614e6d0cd30eaa5725cc852f32)

我改了很多其他东西，不好pr，你先看看，不一定适合你的需求

**Comment by yanm1ng** [comment]
你直接提pr我会适当修改的 (*^__^*)

**Comment by yanm1ng** [comment]
https://github.com/yanm1ng/hexo-theme-vexo/pull/15/commits/d961d19cd786007ec71ed253cbf4a589a769ade6
按你的需要修改了这部分

**Comment by BillyLuo** [comment]
删除了文章之后，tag还在
