### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by noraj** [yanm1ng/hexo-theme-vexo#127]
There are hardcoded Chinese character in the templates eg:

![image](https://user-images.githubusercontent.com/16578570/104437614-4b7b7b00-558f-11eb-9bbe-e02dca8bd5a1.png)

![image](https://user-images.githubusercontent.com/16578570/104437645-57673d00-558f-11eb-8928-c5074329c10d.png)

Another example:

![image](https://user-images.githubusercontent.com/16578570/104437685-66e68600-558f-11eb-926d-f6ec643b904a.png)

**Comment by yanm1ng** [comment]
already fixed
