### ISSUE TITLE
评论框被禁用了

### ISSUE THREAD

**Issue by calvingit** [yanm1ng/hexo-theme-vexo#14]
![image](https://user-images.githubusercontent.com/2109371/28098102-e8e95db2-66e6-11e7-86fe-2d2f40119084.png)

是不是少了一个参数id啊，我看别人那里都加了一个

大部分人是取当前的URL地址：window.location.pathname

**Comment by yanm1ng** [comment]
我排查一下

**Comment by yanm1ng** [comment]
这个问题也同样修复了，是因为没有初始化 issue 的原因

**Comment by calvingit** [comment]
试了一下，没效果呢

**Comment by yanm1ng** [comment]
自己先点击Initialize Comments 先初始化
![image](https://user-images.githubusercontent.com/16443628/28147988-a0c748de-67b6-11e7-8c88-86a4fcf8a697.png)

**Comment by calvingit** [comment]
👌 知道了，但每次生成的一个页面都要自己先去点一下会有点繁琐，有可能自动化吗
