### ISSUE TITLE
page.ejs 裡面的 error image 請求 bug

### ISSUE THREAD

**Issue by ky0ncheng** [yanm1ng/hexo-theme-vexo#18]
`     // error image
    $(".markdown-content img").on('error', function() {
      $(this).attr('src', 'https://xxxx.xxx/xxx.jpg') 
    })`

如果一個圖片刷不出來會瘋狂請求這個 error image，如果這個 error image 也刷不出，就是無限循環了。

另外你主題裡面的這個 error 圖片提示阿里雲報錯了。

**Comment by yanm1ng** [comment]
是的 感谢提醒~

**Comment by yanm1ng** [comment]
不过 master 分支下的我已经改成 http://file.muyutech.com/error-img.png 这张图片了

**Comment by yanm1ng** [comment]
你可以手动替换一下，或者改成你自己准备的图片 O(∩_∩)O

**Comment by ky0ncheng** [comment]
Thx!
