### ISSUE TITLE
文章页最上面的背景图如何替换？

### ISSUE THREAD

**Issue by guangxuan126** [yanm1ng/hexo-theme-vexo#20]
文章页和归档页最上边的背景图该如何替换呢？

**Comment by yanm1ng** [comment]
目前是随机生成的，之后会考虑自定义。当初考虑的时候是因为自己比较懒，写完博客还要找一张配图觉得好麻烦

**Comment by guangxuan126** [comment]
ok，了解。谢谢作者付出~

2017-08-08 16:03 GMT+08:00 yanm1ng <notifications@github.com>:

**Comment by yanm1ng** [comment]
刚刚看了一下不难实现 所以做了一下改进 感谢建议~
