### ISSUE TITLE
可否考虑加上一些其他的格式呢？

### ISSUE THREAD

**Issue by guangxuan126** [yanm1ng/hexo-theme-vexo#23]
类似于引用块的那种格式，比如警告块或者增添一些其他格式呢？
![](https://cloud.githubusercontent.com/assets/9530963/11359678/489a510c-92b9-11e5-9256-341cef6999b6.png)类似这样的

**Comment by YanYuanFE** [comment]
可以参考：https://github.com/pinggod/hexo-theme-apollo

**Comment by guangxuan126** [comment]
@YanYuanFE 那个主题里的格式加了没反应的。。。
