### ISSUE TITLE
我不需要Project和About

### ISSUE THREAD

**Issue by idewindy** [yanm1ng/hexo-theme-vexo#25]
cp -R themes/vexo/_source/* source/
这行命令能取消吗

**Comment by yanm1ng** [comment]
可以

**Comment by idewindy** [comment]
那个tags 我还需要啊 这个可以吗  还有就是我要把文章的详情页，页就是md的容器 去除导航栏下面的容器大小我在哪设置啊

**Comment by yanm1ng** [comment]
那只需要复制 `vexo/_source/` 文件夹下的 tags 文件夹 到 `source/` 目录下就行了

**Comment by idewindy** [comment]
那你干嘛不直接在主题里面写上那个文件夹呢

![70960967-fdad-4f88-9ee3-d5b71a9bdfea](https://user-images.githubusercontent.com/22510807/29515743-2d627f86-86a0-11e7-81ff-9b965a887b20.png)

这个宽度在哪设置啊 最好提供具体位置

**Comment by yanm1ng** [comment]
`vexo/source/css/style.styl` 的 `.app-body`

**Comment by yanm1ng** [comment]
喜欢可以给一个 star 哦 谢谢

**Comment by idewindy** [comment]
@media (min-width:768px) {
	.container {
		width: 750px
	}
}

@media (min-width:992px) {
	.container {
		width: 970px
	}
}

@media (min-width:1200px) {
	.container {
		width: 1170px
	}
}
我可以像这样设置吗

**Comment by yanm1ng** [comment]
不可以 需要用 stylus 的语法，不过你可以在 `vexo/layout/_partial/head.ejs` 通过 <style> 标签定义内部样式

**Comment by idewindy** [comment]
那如果换成 stylus 的语法，该怎么把上面的给写出来啊，就是适配各种屏幕 宽度都不一样

**Comment by yanm1ng** [comment]
issue 是解答问题的，不是教语法的

**Comment by shunhua** [comment]
> 那如果换成 stylus 的语法，该怎么把上面的给写出来啊，就是适配各种屏幕 宽度都不一样

解决了吗？
