### ISSUE TITLE
无法添加Tags页面和About页面

### ISSUE THREAD

**Issue by raphaelli** [yanm1ng/hexo-theme-vexo#26]
非常喜欢你的主题，已经star了，赞
安装后发现无法添加Tags页面和Abouts页面
Project页面已经在_config.yml中关闭，而tags和about我需要
我通过hexo new page "about" 添加的页面是使用也文章模板
请问怎么正确添加，非常感谢

**Comment by yanm1ng** [comment]
手动复制 vexo/_source/ 文件夹下的 tags 文件夹和 abouts 文件夹 到 source/ 目录下就行了

**Comment by raphaelli** [comment]
非常感谢，我觉得这个地方写在readme上比较好吧！
