### ISSUE TITLE
pre/code font-size bug

### ISSUE THREAD

**Issue by ky0ncheng** [yanm1ng/hexo-theme-vexo#3]
![](http://wx4.sinaimg.cn/mw690/6d9bd6a5ly1fgmzvoa8e6j20ku112tat.jpg)

移動版的 pre/code 代碼段字體大小不一致

**Comment by yanm1ng** [comment]
already fixed 😊

**Comment by ky0ncheng** [comment]
@yanm1ng 
![](http://wx2.sinaimg.cn/large/6d9bd6a5gy1fgnlp3resbj212s0n9q6u.jpg)

代碼段裡的字號最後算下來 8.32px，在我的顯示器上面很難看清楚，也沒有受瀏覽器最小 12px 的限制，這個地方是有問題的

**Comment by yanm1ng** [comment]
这个自己定制一下好了，我是觉得和Vue.js官网一样的大小挺好的

**Comment by yanm1ng** [comment]
@ky0ncheng 强制设置了 `font-size`

**Comment by ky0ncheng** [comment]
Thx~
