### ISSUE TITLE
为什么本地预览时主页不显示文章？

### ISSUE THREAD

**Issue by guangxuan126** [yanm1ng/hexo-theme-vexo#31]
新建一篇文章后，突然本地预览就显示空白了，hexo s。 但是传到主机上之后，可以显示文章列表。。
![](https://gxuann.org/1.png)

**Comment by ky0ncheng** [comment]
hexo clean && hexo g && hexo d

**Comment by guangxuan126** [comment]
hexo d不就上传服务器了？服务器里正常。但是hexo s本地预览主页空白。。标签页啥的都正常……

**Comment by ky0ncheng** [comment]
本地server強制https了？

**Comment by guangxuan126** [comment]
这个怎么看呢？服务器上开了https

**Comment by ky0ncheng** [comment]
看看瀏覽器的console信息

**Comment by yanm1ng** [comment]
plz go to see [hexo doc](https://hexo.io/docs/)
