### ISSUE TITLE
code样式不显示

### ISSUE THREAD

**Issue by ZeoZhang** [yanm1ng/hexo-theme-vexo#40]
![](http://ww1.sinaimg.cn/large/be29fb3cgy1fjzezh1d0aj22060co42k.jpg)
http://ww1.sinaimg.cn/large/be29fb3cgy1fjzezh1d0aj22060co42k.jpg
为什么```<code></code>```的样式不现实呢？

**Comment by ky0ncheng** [comment]
```
```
