### ISSUE TITLE
Can't display the blank lines in code block correctly

### ISSUE THREAD

**Issue by purpleskyfall** [yanm1ng/hexo-theme-vexo#45]
I'm using hexo-theme-vexo released at 2017-09-21.

When I applied this theme for [my blog site](www.gnss.help), I found that when render code blocks, it couldn't display the blank lines correctly. Also, the **syntax highlighting of bash** program language was incorrect.

**Comment by yanm1ng** [comment]
fixed in #42

**Comment by yanm1ng** [comment]
you can download the latest release https://github.com/yanm1ng/hexo-theme-vexo/releases/tag/v2.2
