### ISSUE TITLE
代码块样式更改

### ISSUE THREAD

**Issue by whjin** [yanm1ng/hexo-theme-vexo#51]
题主，你好。非常感谢你设计的这个主题，我正在使用，感觉不错。但是代码块需要设置很不方便，因为Markdown本身提供缩进代码块，非常方便。

\```css
代码内容
\```

所以，请教题主如何修改样式进行更换。

原来的样式：
\```javascript
var a = {n: 1};
var b = a;
a.x = a = {n: 2};
console.log(a.x);//undefined
console.log(b.x);//{n: 2};
\```
期望的样式：
缩进    var a = {n: 1};
缩进    var b = a;
缩进    a.x = a = {n: 2};
缩进    console.log(a.x);//undefined
缩进    console.log(b.x);//{n: 2};

**Comment by yanm1ng** [comment]
我这里比较难复现，如果可以的话你可以把你的markdown文件发到我邮箱试试
