### ISSUE TITLE
Projects页显示问题

### ISSUE THREAD

**Issue by doctording** [yanm1ng/hexo-theme-vexo#83]
应该是显示star最多的6个github repo，看代码也是如此，但是实际运行却有些star明明最多却没有显示在那6个repo中。

我想此6个repo应该是与自己github主页上的6个repo一致的是比较好的做法, 应该有个默认的（因为github可以自己设置自己首页上的显示）

我的修改：https://github.com/doctording/hexo-theme-vexo/blob/dwl/layout/project.ejs

**Comment by yanm1ng** [comment]
good👍
