### ISSUE TITLE
作者考虑添加灯箱效果吗？

### ISSUE THREAD

**Issue by Windmzx** [yanm1ng/hexo-theme-vexo#9]
文章中大图有时候看不清，后续会添加灯箱（点击放大）的效果吗？谢谢

**Comment by yanm1ng** [comment]
感谢 Issue，这也是我最近想做的一个功能

**Comment by yanm1ng** [comment]
已经加了，不知道有没有未知的bug

**Comment by yanm1ng** [comment]
[commit-log](https://github.com/yanm1ng/hexo-theme-vexo/commit/8cdfa7176ddcfd225b1744ce1816afa7daa38cf2)
