### ISSUE TITLE
<css>提示的相关问题【本人小白，多多指教】

### ISSUE THREAD

**Issue by CNDoge** [yanm1ng/hexo-theme-vexo#98]
![image](https://user-images.githubusercontent.com/47162655/52056512-708ea300-259d-11e9-94c4-d4dd5a54e12b.png)
就这上面有一行字，这么好的主题不知道我做错了哪里，问问大佬
谢谢了

**Comment by huoher** [comment]
修改themes目录下/vexo/_partial/head.ejs文件，找到
```
css('css/plugins/gitment.css')
```
这一行，在这行改为
```
<%-  css('css/plugins/gitment.css')  %>
```
即可

**Comment by huoher** [comment]
> ![image](https://user-images.githubusercontent.com/47162655/52056512-708ea300-259d-11e9-94c4-d4dd5a54e12b.png)
> 就这上面有一行字，这么好的主题不知道我做错了哪里，问问大佬
> 谢谢了
修改themes目录下/vexo/_partial/head.ejs文件，找到

```
css('css/plugins/gitment.css')
```
这一行，在这行改为

```
<%-  css('css/plugins/gitment.css')  %>
```
即可
